version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
  # the below could be utilized alongside
  # docker attach, but i prefer exec -it
  #tests:
    #build:
    #  context: .
    #  dockerfile: Dockerfile.dev
  #  volumes:
  #    - /app/node_modules
  #    - .:/app
  #  command: ["npm", "run", "test"]
